# Generated by Django 4.2 on 2023-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["date_added"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
